#!/bin/bash
PKG_NAME=oresat-star-tracker
rm -rf /usr/share/$PKG_NAME
rm -rf /usr/share/doc/$PKG_NAME
rm -f /lib/systemd/system/oresat-star-tracker.service
rm -f /usr/share/dbus-1/system.d/org.OreSat.StarTracker.conf
rm -f /run/$PKG_NAME.pid
if [ "$1" = "purge" ]; then
	rm -rf /tmp/$PKG_NAME
fi
systemctl daemon-reload