#!/bin/bash

parent_path=$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )
top_level=$parent_path/..

BUS_ID=vcan0

echo "Checking virtual can interface $BUS_ID exists" 

if sudo ifconfig $BUS_ID > /dev/null ; then 
    echo "Found $BUS_ID."
else 
    sudo ip link add dev vcan0 type vcan
    sudo ip link set vcan0 up
fi

cd $top_level
sudo python3 -m oresat_star_tracker
